### ISSUE TITLE
ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by cathyhax** [MatteoGabriele/vue-analytics#113] opened 2018-04-19 03:34 UTC
Hi there,

Set everything up as directed and I'm getting this error: 

https://www.google-analytics.com/analytics.js net::ERR_NAME_NOT_RESOLVED
 [vue-analytics] An error occured trying to load https://www.google-analytics.com/analytics.js. Please check your connection.

If you could help me it'd be much appreciated!

Best,
Cathy

**Comment by MatteoGabriele** [comment] 2018-04-19 05:54
Hi @cathyhax could you let me know which version are u running and a snippet of your plug-in installation

Thanks

**Comment by michael-alade** [comment] 2018-04-22 19:57
I am having this same problem. But I am using Nuxt module with version 2.0.2

**Comment by cathyhax** [comment] 2018-04-24 04:09
Hi Matteo,

I am running "vue-analytics": "^5.10.2".

I have the following in my main.js file:

```
import VueAnalytics from 'vue-analytics'
import router from './router'

Vue.use(VueAnalytics, {
  id: 'UA-1234567',
  router,
  autoTracking: {
    screenview: true
  }
})

new Vue({
  el: '#app',
  router,
  axios,
  store,
  render: h => h(App)
})
```
Any help would be greatly appreciated!

Cathy

**Comment by MatteoGabriele** [comment] 2018-04-24 07:14
@cathyhax I can't reproduce this error, but I was wondering if you are using some AD blocker or Analytics blocker in your browser. I would suggest to try in a private browser and check if you still have the same error or I need you to create a small application with `vue-cli` and reproduce this error and make it public so that I can have a look.

thanks for your time

**Comment by MatteoGabriele** [comment] 2018-04-24 09:37
@michael-alade I thought so: that error is usually prompt when the script cannot be loaded and usually is due to a connection error, but also ad blockers.
I might go to add another line to the error description so that people checks also blockers in their browsers.

@cathyhax I will close this ticket because I believe you have the same issue, otherwise feel free to re-open it with a reproduction.

Thanks :)

**Closed by MatteoGabriele** 2018-04-24 09:37 UTC
Labels: need more info, reproduction needed

**Comment by robsonsobral** [comment] 2019-06-18 02:00
Hi, @MatteoGabriele !

Is there a way to prevent the loading of a script in case of an ad blocker?

**Comment by MatteoGabriele** [comment] 2019-06-18 05:31
@robsonsobral Can you be more specific?

**Comment by robsonsobral** [comment] 2019-06-20 18:24
Just to avoid the "[vue-analytics] An error occured! Please check your connection, if you have any Google Analytics blocker installed in your browser or check your custom resource URL if you have added any." in case of an ad blocker.

In case of a blocked connection to Google Analytics, do not even try to load the script.
