### ISSUE TITLE
`this` not bound to command

### ISSUE THREAD

**Issue by wdmtech** [MatteoGabriele/vue-analytics#93] opened 2018-02-08 12:34 UTC
I'm trying to consolidate all my URL clicks into one command like so:

```html
<a v-for="site in social"
   :href="site.url"
   class="navbar-item"
   v-ga="$ga.commands.trackClicked.bind(this, site.url)"
   @click="logClicked(site.url)"
   target="_blank"
   :key="social.indexOf(site)">
     ...
</a>
```

Here is my command declaration:

```js
Vue.use(VueAnalytics, {
  id: 'UA-BLAH-69',
  fields: { userId },
  autoTracking: {
    exception: true
  },
  commands: {
    trackClicked (name = 'unknown') {
      this.$ga.event('clicks', 'click', 'url', name)
    }
  }
})
```

As you can see below, `this` is not bound to the method:

![image](https://user-images.githubusercontent.com/7282262/35973175-bbe2c5f8-0cd4-11e8-8d27-f6a99d41ee86.png)

I'm probably doing something wrong (or misunderstanding the use of the directive!)

Any ideas?

**Comment by MatteoGabriele** [comment] 2018-02-08 13:22
hi @wdmtech 
it should work. Could you please create a small public repo with vue-cli where you re-create this error and then send the link to me?

thanks a lot

**Comment by wdmtech** [comment] 2018-02-08 18:32
Aha! I made a small test case and it worked, so I compared it to my project, and I believe it's because my links are in a v-for that's on the same element as the `$v-ga` directive

The following is working in my project:

```html
          <a
             href="https://google.com"
             class="navbar-item"
             v-ga="$ga.commands.trackClicked.bind(this, 'thingy')"
             target="_blank">
               bleh
          </a>
```

I tried moving the loop to a parent element, which had the same error as above:

```html
          <button v-for="site in social" :key="social.indexOf(site)">
            <a
              :href="site.url"
              class="navbar-item"
              v-ga="$ga.commands.trackClicked.bind(this, site.url)"
              @click="logClicked(site.url)"
              target="_blank"
              >
              <span class="icon"><i class="fa" :class="site.icon"></i></span>
            </a>
          </button>
````

**Comment by wdmtech** [comment] 2018-02-08 18:41
Here you go 👍 

[https://github.com/wdmtech/vue-analytics-ga-directive-test](test repo)

**Comment by MatteoGabriele** [comment] 2018-02-15 11:46
@wdmtech the problem is just that when you are inside a v-for loop, the context changes and to refer to your component, you need to use the `$parent` property that Vue provides.

so in your case will be 

```html
   <ul>
      <li v-for="link in links">
        <button v-ga="$ga.commands.trackClicked.bind($parent, link)">
          {{ link.url }}
        </button>
      </li>
    </ul>
```

I already have a ticket that suggests to have direct access to the $ga object inside the commands functions, so I will close this ticket.

I hope everything is clear and thanks for your feedback

**Closed by MatteoGabriele** 2018-02-15 11:46 UTC
Labels: reproduction needed

**Comment by mstrofbass** [comment] 2019-01-29 08:00
Just ran into this issue. Is this noted anywhere in the docs? If not, can it be added (e.g., to the v-ga page)?
