### ISSUE TITLE
Command ignored. Unknown target: undefined

### ISSUE THREAD

**Issue by foundryspatial-duncan** [MatteoGabriele/vue-analytics#22] opened 2017-04-06 17:22 UTC
I've got a single-page app and I'm *not* using vue-router. Since it's not using a router, I'm trying to manually fire `trackPage` in the root component, but the Google Analytics Debug Chrome extension is saying "Command ignored. Unknown target: undefined":

```
Running command: ga("send", "pageview")
2017-04-06 10:15:28.202 analytics_debug.js:10 Command ignored. Unknown target: undefined
```

This app is using the vue-cli `webpack-simple` template, so my main entry point looks like this:

```
import Vue from 'vue';
// vue-analytics
import VueAnalytics from 'vue-analytics';
// main app / layout component
import App from './components/App.vue';
// vuex store
import store from './store';

Vue.use(VueAnalytics, {
    id: 'UA-1234-1234', // example
});

new Vue({ // eslint-disable-line no-new
    el: '#app',
    store,
    render: h => h(App),
});
```

and the root component, `App.vue` has this:

```
    mounted() {
        this.$ga.trackPage('/', 'App', window.location.href);
    },
```

Can you think of any reason why this wouldn't work? Is vue-router required for this plugin?

**Comment by MatteoGabriele** [comment] 2017-04-06 17:54
Hi @foundryspatial-duncan 
vue-router is not mandatory, I'll have a look right now to see if I can find something, otherwise I'll gonna ask maybe to share a reproduction of the error.

Thanks!

**Comment by MatteoGabriele** [comment] 2017-04-06 18:20
I can't reproduce the `Command ignored. Unknown target: undefined` but I do see that calling the track event from the `mounted` component can cause issues: can happen that it doesn't track because the Google Analytics script is not loaded yet. The application booting is faster.

You might want to wait until the script is loaded and mount your application using the callback function in the options

```js
Vue.use(VueAnalytics, {
  id: 'UA-12345678-9',
  onAnalyticsReady () {
    app.$mount('#app')
  }
})
```

**Comment by MatteoGabriele** [comment] 2017-04-12 10:21
@foundryspatial-duncan I'm closing this ticket. Feel free to open it again if you still have the same problem

**Closed by MatteoGabriele** 2017-04-12 10:21 UTC
Labels: in confirm

**Comment by aschalund** [comment] 2018-07-12 20:30
So i know this is a closed ticket but I am experiencing a similar thing.  I am using router but I have an issue where any tracking calls that are made in created() or mounted() trigger this error `Command ignored. Unknown target: undefined` and do not record to GA. Looking at the debugging tool it looks like they are firing before the app inits GA logging. 

Here is my router code
`Vue.use(VueAnalytics, {
  id: 'UA-ID',
  router,
  checkDuplicatedScript: false,
  autoTracking: {
    exception: true
  },
  debug: {
    enabled: true
  }
})`


Just doing some basic calls for custom dimensions and events etc
`this.$ga.set('dimension3', 'dimension3Data')`


Hoping someone has some insight to this.

**Comment by outOFFspace** [comment] 2020-05-22 14:25
setTimeout only helps:
`trackPageLoad() {
                const timeout = setTimeout(() => {
                    this.$ga.commands.trackEvent.apply(this, ['Search_Rashirenyi_poisk', 'Prosmotr_stranitsy', 'Forma_poiska']);
                    clearTimeout(timeout);
                }, 0);
            }`
