### ISSUE TITLE
No Events Firing At All

### ISSUE THREAD

**Issue by domface** [MatteoGabriele/vue-analytics#132] opened 2018-06-17 22:11 UTC
Okay so, I've been banging my head on this all week and can't figure out WTF is going on.

I've read all issues regarding new accounts, so I've waited a few days to let the new account thing simmer, but i still encounter this issue:

Google Analytics can sense that a user is active on the page, and is active at my NON Vue.js endpoints (i.e. a static admin page).

The only thing i get is, that a user is on the index page '/' but no more granularity beyond that in my vue.js app.

I've also tried manually adding a bunch of events throughout the app, and those events are also not registering.

When i open my console in Safari, and enter the following:

```
if ("ga" in window) {
    tracker = ga.getAll()[0];
    if (tracker)
        tracker.send("event", "Test", "Test GA");
}
```
Google Analytics does fire the event in my analytics page.

My Config is as follows:

```
Vue.use(VueAnalytics, {
  id: 'UA-XXXXXXX-1',
  linkers: ['localhost:8080', 'dev.foo.co', 'foo.co'],
  router: router,
  debug: {
    enabled: true,
    trace: true,
    sendHitTask: true
  },
  autoTracking: {
    exception: true,
    screenview: true,
    transformRouteParams: true,
    pageviewTemplate(route) {
      return {
        page: route.path,
        title: document.title,
        location: window.location.href
      }
    }
  },
})



/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  components: { App },
  template: '<App/>'
})

```

In my component with the custom this.$ga tracking i have:

```

gaClick(name) {
        console.log('clickk')
        this.$ga.event({
          eventCategory: 'trackCategory',
          eventAction: 'click',
          eventValue: name
        })
      }

```

When debug mode is on, i do see the events firing in the console, but nothing in my google analytics account. But again, when i rerun the sample event in my console, it does register in GA.

Any ideas????

**Comment by MatteoGabriele** [comment] 2018-06-18 07:13
Unfortunately, I don't know what's causing this.
I've just re-tested with a new app, added the plugin and my personal GA domain ID and I can track myself locally in real-time as expected

![screen shot 2018-06-18 at 9 08 44 am](https://user-images.githubusercontent.com/5337152/41522739-ae890b42-72d7-11e8-88ea-a434e91bca24.png)

only think we can try is if you create a simlpe application with vue-cli, very minimal setup just the necessary to run it, you add your plugin configuration and see if it works or not.
if it doesn't, make this repo public to me here and I'll check.

Other then this I'm afraid I can't do much

cheers

**Comment by Arredatore** [comment] 2018-07-04 06:51
Hi, I have the same hard to repeat issue. 

Although, it is working in a private browser instance indeed, thank you that was helpful. So the question of mine which extensions may cause this to not working? How popular are they, have you done any testings?

**Comment by MatteoGabriele** [comment] 2018-07-04 06:56
Most of the times is adblcok or some Google analytics blockers, but you never know when too many plugins that don't know each other start doing stuff under the hood, something must go wrong.

**Comment by Arredatore** [comment] 2018-07-04 09:39
So, in my case, I've updated the Vue-CLI and vue/cli-plugin-pwa to the last version and everything works now.
Probably the service worker was the issue.

**Comment by MatteoGabriele** [comment] 2018-07-04 10:35
Thanks everyone for the feedback, looks like is not a plugin issue so far and the owner of issue didn't send any reproductions for 2 weeks so I will close this ticket.

feel free to re-open this ticket with a reproduction

cheers!

**Closed by MatteoGabriele** 2018-07-04 10:35 UTC
Labels: reproduction needed

**Comment by domface** [comment] 2018-07-09 18:50
I found a way to reproduce!

**Comment by cymiranda3** [comment] 2019-11-13 07:39
> I found a way to reproduce! After commenting out `autoTracking`, it now works.

Just want to point out that this also solved this issue for me... I think the documentation just needs to be reworded because the assumption is that that code chunk should be included w/o any further configuration, when I assume some is necessary (which is why nothing was being sent)?
