### ISSUE TITLE
this.$ga.enable() does not work (undefined)

### ISSUE THREAD

**Issue by maxleistner** [MatteoGabriele/vue-analytics#234] opened 2019-08-13 13:38 UTC
vue@2.6.10 
vue-analytics@5.17.0

I am calling `this.$ga.enable()` function within created within a component. 
GA Analytics is disabled from the main.js file and should now be enabled after reading the contents of a cookie file.

main.js
```
 Vue.use(VueAnalytics, {
  id: 'UA-144752596-2',
  set: [
    { field: 'anonymizeIp', value: true }
  ],
  disabled: true,
  router
})
```

Component (Part of export default)
```
created: function () {
      const cookieTrackingValue = this.$cookie.get('enable-tracking')

      if (cookieTrackingValue === 'false') {
        this.$cookie.set('show-cookie', 'false', 25)
      } else {
        this.$ga.enable()
      }
    }
```

Cookie "enable-tracking" not present

Error after page load:
`[Vue warn]: Error in created hook: "TypeError: Cannot read property 'enable' of undefined"`

<img width="1436" alt="Bildschirmfoto 2019-08-13 um 15 44 23" src="https://user-images.githubusercontent.com/7567185/62946594-49811b80-bde1-11e9-8036-56f3c283e238.png">

**Comment by maxleistner** [comment] 2019-08-13 13:45
Added Screenshot

**Comment by MatteoGabriele** [comment] 2019-08-18 15:05
I'm sorry but the enable/disable feature works and I can't reproduce this error.
I'm able to set it disabled by default and then re-enable it.

I'm going to close this one, if you still have it and have time for a reproduction, please feel free to reopen it

thanks :)

**Closed by MatteoGabriele** 2019-08-18 15:05 UTC
