### ISSUE TITLE
New Sessions generated constantly

### ISSUE THREAD

**Issue by cspeer** [MatteoGabriele/vue-analytics#94] opened 2018-02-08 16:42 UTC
### Description

Hi there,

I'm not sure where this is coming from and as I've exhausted my resources I'm turning to you.
What I'm seeing is some very weird behavior. Please take a look at this Google Analytics evaluation:
<img width="1474" alt="screenshot 2018-02-08 14 46 39" src="https://user-images.githubusercontent.com/326824/35985242-7c1e69c8-0cf6-11e8-8aea-7f1d33373554.png">
<img width="1757" alt="screenshot 2018-02-08 14 46 57" src="https://user-images.githubusercontent.com/326824/35985243-7c3c68e2-0cf6-11e8-8a26-695282bd9e3f.png">

This is one user, but essentially all our user profile look the same: new session after new session after new session.
Do you have any idea @MatteoGabriele ?
The one thing that we didn't do so far, is give our routes names in VueRouter. I'm also not so sure why you'd need them in the first place, as the [documentation](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md) doesn't give any explanation. Could that be it?

### Expected behavior

Not have a lot of new session per user in a very small time frame.

### Actual behavior

See above

### Environment

vue-analytics@5.8.0

### Reproducible Demo
--

Cheers,
Chris

**Comment by MatteoGabriele** [comment] 2018-02-08 16:56
Hi @cspeer 
I was reading the documentation again and I admit that the auto-tracking part doesn't sounds super straight forward from outside: gonna try to rewrite few parts.

Yes, you should actually use routing with a name for auto-tracking:
* it is used here as title of your tracked page https://github.com/MatteoGabriele/vue-analytics/blob/master/src/lib/page.js#L44-L49
* I gave it for granted because I usually use `router-link` pointing on a route name, not at a path. 

Not sure if this can be the reason

**Comment by MatteoGabriele** [comment] 2018-02-08 17:02
But I think that the missing name, cannot be the reason of your multiple sessions
have a read [here](https://support.google.com/analytics/answer/2731565?hl=en) if you haven't done yet.

**Comment by cspeer** [comment] 2018-02-08 17:10
Thanks for the speedy reply. I've read the resource from Google you pointed out before, but I can't see what might go wrong. We implement your library in a standard way. Nothing out of the ordinary, no hacks. It also only has like 6 public routes.

So are you saying that the name attribute only serves that one purpose that you highlighted there?
Regardless, I have now added names to all our routes. I guess it'll take some time until we can determine whether this makes a difference or not. I'll check back in with you tomorrow!

**Comment by MatteoGabriele** [comment] 2018-02-08 19:41
I'm actually not 100% sure about it, since I have never experienced such issue. The plug-in is just a Google analytics with some automation to make developer life easier: nothing fancy going on in the background.

Sorry it I can't help you more. 
Let me know

**Comment by cspeer** [comment] 2018-02-12 09:33
Aright, the weekend has passed but adding `name` didn't make any difference to our analytics. I'm stuck. And I'm sorry but I don't have any further information for you.
I'll probably kick out vue-analytics and try including the standard Google Analytics lib and see if it makes a difference. If it does, we can be certain that it's something within your lib. I'll get back to you as soon as I know more. Thanks for your efforts @MatteoGabriele!

**Comment by MatteoGabriele** [comment] 2018-02-12 09:44
Hi @cspeer 
I'm sorry for that, but yes please let me know if does fix your issue, so that I can see what's going on in the library.

I am 90% sure that shouldn't be the library because nothing really happens at the end and nobody complained about this in the last year: but never say never!

Thanks for your time

**Comment by cspeer** [comment] 2018-02-12 09:47
I know! It's so weird. Especially since we do nothing out of the ordinary.
Here's my config, just in case:
`
.use(VueAnalytics, {
    id: 'UA-*********',
    router,
    debug: {
      enabled: false,
      trace: false,
      sendHitTask: process.env.NODE_ENV === 'production'
    }
  })
`

**Comment by MatteoGabriele** [comment] 2018-02-12 09:51
The configuration looks normal to me.
You could enable debug if it's not production, so that you might spot something in your console and the trace is false by default, you can remove it if you want.

I always have `debug.enabled` on `process.env.NODE_ENV !== 'production'`

**Comment by MatteoGabriele** [comment] 2018-02-15 10:05
@cspeer any news about it :)

**Comment by cspeer** [comment] 2018-02-16 09:12
Sorry, I didn't have the time to change anything yet. I might get to it today. I'll let you know!

**Comment by MatteoGabriele** [comment] 2018-02-16 10:06
@cspeer no worries! thanks

**Comment by cspeer** [comment] 2018-02-19 09:16
Alright @MatteoGabriele here's an update:
Because I couldn't figure out what's wrong I switched over to https://github.com/ScreamZ/vue-analytics and boom, now everything in our stats is normal.
Meaning there must be something in your implementation that is not right, causing this weird type of behaviour. I'm sorry that I don't have any more information :(

**Comment by MatteoGabriele** [comment] 2018-02-19 10:06
mmmm yeah not really helpful, but yeah I will see what I can find.
no idea!

thanks anyway :)

**Comment by MatteoGabriele** [comment] 2018-02-19 18:23
I went to check the code of the other package but it does nothing special, so I don't really get it.

I'm using the basic initial google analytics configuration.

If you can't share other data or thoughts, besides that, I'm going to close it and wait that someone else has a similar issue.

thanks

**Comment by cspeer** [comment] 2018-02-20 08:23
yeah, sure. I understand. Thanks for your efforts :)

**Comment by MatteoGabriele** [comment] 2018-02-20 09:30
Thanks to you for the feedback, I'll keep an eye on this.

**Comment by psnoonan** [comment] 2018-03-05 22:16
My company is in the process of migrating our sites to Nuxt, and we are seeing the same analytics behavior using this plugin. Our number of sessions is going way up, and our pages per session are going way down. Also, as in the images @cspeer posted above, the source is alternating between organic search and paid search for some reason.

![analytics](https://user-images.githubusercontent.com/7296414/37001741-bed10d10-2084-11e8-8060-eab259edd0ee.png)

![sessions](https://user-images.githubusercontent.com/7296414/37001742-bf0794a2-2084-11e8-9872-b4b1fa6b9765.png)

**Comment by MatteoGabriele** [comment] 2018-03-05 22:27
@psnoonan Thanks for that. I will try to understand why it's happening.
If u have any suggestions, they are more then welcome

**Comment by cspeer** [comment] 2018-03-05 22:45
Are you currently running an ad campaign on Google AdWords @psnoonan?
We were at the time and still are. Might this have to do with anything?

**Comment by psnoonan** [comment] 2018-03-05 23:27
@cspeer I believe we are always running a campaign. It doesn't seem to me like that should affect this plugin, though, I've been surprised often enough before.
@MatteoGabriele I am requesting more info from the SEO department so I can narrow down what is causing this, but I can tell you that some of the links (nuxt-link) on the site are using an object with name and params, and some are using a hard-coded path.

**Comment by MatteoGabriele** [comment] 2018-03-06 08:19
@cspeer  @psnoonan thanks a lot for your support: would be really super helpful to understand why this is happening, also because that's not much going on under the hood, but I'm probably missing something really stupid that is causing this problem.  

For me right now it is also hard to test because I don't have any domain to test, so I don't have access to any stats. Only trying now with the demo account of Google Analytics but I'm not sure if it's reliable trying there because it's a public account basically.

**Comment by cspeer** [comment] 2018-03-06 08:29
Yeah I know @psnoonan it's a reach, but since the constant switch between organic and paid search is something that sticks out, I thought it might be worth looking into.

@MatteoGabriele What you could do though is install https://github.com/ScreamZ/vue-analytics on a test site and record what it does with the Google Analytics debug tool and then do the exact same thing with your plugin present. Then you can compare both and work your way backwards.

Also, apart from simply recording page views, we used your plugin to send events for goals back to GA. I don't know if that's something you do @psnoonan but it might be worth it looking into what's being sent here too and whether it makes a difference if you don't record events at all.

**Comment by MatteoGabriele** [comment] 2018-03-06 09:15
@cspeer I've actually looked at his code and there's nothing more or nothing less in the configurations of the trackers, but I will try to install it and see what he's sending. The odd part is that I know exactly what I am sending and from the logs looks pretty normal to me.

I'll keep searching for something.

**Comment by cspeer** [comment] 2018-03-06 09:18
Yeah, I too looked at both code bases and didn't find a anything. Hence my debug output comparison suggestion. Good luck!

**Comment by MatteoGabriele** [comment] 2018-03-06 09:49
@cspeer @psnoonan only different thing I see, is that by default vue-ua uses 
* screenview and I use pageview
* appName and appVersion as mandatory fields
* transport "beacon" (which is actually deprecated)

that's it. I could try to add a check if you want screenview or pageview and then see if that one helps, but the documentation of Google Analytics for page tracking always uses pageview, so I'm not sure, but adding it as a feature is not bad either way

**Comment by cspeer** [comment] 2018-03-06 09:52
https://github.com/ScreamZ/vue-analytics/pull/24
Switching between page and screen view is already built-in. I wrote the code since we needed that for our site. Didn't make any difference in regards to the issue at hand though, it works as expected.

**Comment by psnoonan** [comment] 2018-03-06 14:01
- I'm using Nuxt with server-side rendering
- My site's navigation is built dynamically and uses path links `to="/search/new"`
- Other links on the site are passing objects `:to="{ name: 'search', params: { type: 'new' } }"`
- I am using the plugins auto page tracking feature
- I am also sending custom page views `$ga.page`
- I am also sending custom events `$ga.event`
- On the Google side, my company is using custom goals, ad campaigns, and tag manager

That is a lot to narrow down. If I have time, I'm going to try and build a small test site with all those interactions, host it on a free Heroku account, and see if I can control when the new sessions happen.

**Comment by MatteoGabriele** [comment] 2018-03-10 17:53
@cspeer @psnoonan any luck?

I've been doing some tests, but unfortunately nothing new so far: i can't reproduce it.
I'm also doing a refactor of the codebase in general and i will probably release a beta soon that you could try, but so far no luck.

**Comment by psnoonan** [comment] 2018-03-12 19:35
@MatteoGabriele I have not been able to reproduce it on my own either. I've tried everything I can think of to match my company's site and it still isn't splitting the sessions up the same way. You can see what I've tried on the test site: https://github.com/psnoonan/session-bug-test

**Comment by MatteoGabriele** [comment] 2018-04-15 12:05
This issue still doesn't have any reproductions that show the issue and therefore is not possible to be fixed. 
I will close it again. 
Please re-open it **only** in case of a repository that proofs this actual behavior. I will obviously keep an eye on it during other projects to see if pops up but so far it didn't.

thanks again all for suggestions and feedback :)

**Closed by MatteoGabriele** 2018-04-15 12:05 UTC
Labels: P1: Urgent, help wanted, high priority, need more info

**Comment by dijs** [comment] 2019-02-08 23:11
@psnoonan Did you ever figure out a fix to this issue? I am seeing the *exact* same problem but in a React project. 

Please let me know if you found a solution.

**Comment by cspeer** [comment] 2019-02-08 23:25
Sorry no I didn't @dijs. I had to switch to a different plugin. https://github.com/ScreamZ/vue-analytics

**Comment by psnoonan** [comment] 2019-02-09 01:25
@dijs No I didn't. If I remember correctly, I moved back to a previous version that worked.

**Comment by iustin-gheorghe** [comment] 2021-11-24 12:54
@psnoonan We are currently migrating one of our apps to Nuxt, and after adding new properties to the analytics account, we are facing the same issue: the new properties get random sessions generated. 

![image](https://user-images.githubusercontent.com/63230351/143242120-54194559-8584-484c-b80f-b4a4685b775b.png)

We can't use the [other plugin](https://github.com/ScreamZ/vue-analytics) because it doesn't seem to support multiple properties and different user samplings.


If you managed to fix this by downgrading the dependency version, could you please let us know which version is working?

Thank you!

**Comment by psnoonan** [comment] 2021-11-24 17:22
> @psnoonan We are currently migrating one of our apps to Nuxt, and after adding new properties to the analytics account, we are facing the same issue: the new properties get random sessions generated.
>  
> We can't use the [other plugin](https://github.com/ScreamZ/vue-analytics) because it doesn't seem to support multiple properties and different user samplings.
> 
> If you managed to fix this by downgrading the dependency version, could you please let us know which version is working?
> 
> Thank you!

@iustin-gheorghe 
we don't have complex analytics needs on our Nuxt 2 sites, so we moved away from using any analytics package and created our own plugin.

In the plugin (which is only loaded on client), we initialize using Google's provided script, then track pageviews using the following:
```
app.router.afterEach((to, from) => {
    ga('set', 'page', to.fullPath);
    ga('send', 'pageview');
});
```

Then to track events we use a helper method:
```
export const trackGoogleEvent = ({
    category = 'lead',
    event = 'start',
    label,
}) => {
    ga('send', 'event', category, event, label);
};
```

**Comment by iustin-gheorghe** [comment] 2021-11-25 12:03
I see, that's was our next step also. Thanks a lot for getting back!
