### ISSUE TITLE
Programmatically disabling/enabling tracking

### ISSUE THREAD

**Issue by josh-king** [MatteoGabriele/vue-analytics#213] opened 2019-05-08 23:15 UTC
### Description

My current build is using nuxt.js - I have tried the specific wrapper module but it seems to produce the same issue. Whenever I try to disable on the fly and then check the real time tracking I can still see a user connected and all the page events that user is sending.

### Expected behavior

When disabling using the 'this.$ga.disable' call, K should not longer be able to see a user connected.

### Actual behavior

I can still see all page events from the user.

### Environment

Run this command in the project folder and fill in their results:

//TODO: When I get back to a pc
`npm ls vue-analytics`: 

Then, specify:

1. Operating system:
2. Browser and version:

### Reproducible Demo

// TODO: I will create another test environment to show the tracking

Am I interpreting the commands correctly? Should I still be able to see the user being tracked?

**Comment by josh-king** [comment] 2019-05-08 23:17
* programmatically

**Comment by MatteoGabriele** [comment] 2019-05-09 06:08
no you shouldn't. the command turns off analytics using its own global variable and all events are aborted. 
You can see the code here
https://github.com/MatteoGabriele/vue-analytics/blob/master/src/no-ga.js#L9

**Comment by josh-king** [comment] 2019-05-09 08:13
Thanks for the reply - I'll get a build up and running soon - however until then do you have a project where this is working?

**Comment by MatteoGabriele** [comment] 2019-05-09 08:17
No I don't, but last time I check was working and I never touched that part again since the first time I published it

**Comment by josh-king** [comment] 2019-05-09 08:23
Okay - it may be how nuxt loads the plugin as the tracking code is defined in the plugin file which if I'm correct is loaded once as the start

**Comment by MatteoGabriele** [comment] 2019-05-09 08:28
Yeah I'm not super sure about Nuxt. I personally never used it, I just made that wrapper plug-in but this plug-in came first and I always develop it based on a normal non-ssr application, even if I try to be ssr friendly.

**Comment by MatteoGabriele** [comment] 2019-05-09 08:29
Your reproduction should be based on a simple as possible Vue app. Basic Vue, no Nuxt. If you have Nuxt specific issues you might want to drop it in the other repo and I'll take it from there but it's quite tough to make "everyone" happy sometimes

**Comment by josh-king** [comment] 2019-05-09 08:35
Sure no problem - I have added a bug report on the nuxt module version, however, now that I look over it again, I can see it has been reported a couple of times that programmatically disabling/enabling is not working (just not reported correctly)

**Comment by josh-king** [comment] 2019-05-09 08:41
https://github.com/nuxt-community/analytics-module/issues/49#issue-441740887

Link to the issue raised on the module wrapper

**Comment by MatteoGabriele** [comment] 2019-06-10 15:37
I'm closing this one because has been already opened in the nuxt module repo 

thanks for your feedback

**Closed by MatteoGabriele** 2019-06-10 15:37 UTC
