### ISSUE TITLE
Could not find a declaration file for module 'vue-analytics'.

### ISSUE THREAD

**Issue by jongbonga** [MatteoGabriele/vue-analytics#230] opened 2019-07-29 05:45 UTC
I'm getting a

Could not find a declaration file for module 'vue-analytics'. '/Users/jonathan/Code/odbf/node_modules/vue-analytics/dist/vue-analytics.js' implicitly has an 'any' type.
  Try `npm install @types/vue-analytics` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-analytics';`

on import

**Comment by litagaki** [comment] 2019-08-01 00:37
This looks like a duplicate of https://github.com/MatteoGabriele/vue-analytics/issues/161
I ended up using the advice there to create my own declaration file 'vue-analytics.d.ts' which has content as follows:

> ```ts
>import _Vue, { PluginFunction } from 'vue';
>
>declare class VueAnalytics {
>  static install(Vue: typeof _Vue, options: any): void;
>  analyticsMiddleware: any;
>  onAnalyticsReady: any;
>  commands: any;
>  event: any;
>  ecommerce: any;
>  set: any;
>  page: any;
>  query: any;
>  screenview: any;
>  time: any;
>  require: any;
>  exception: any;
>  social: any;
>  disable: any;
>  enable: any;
>}
>
>export default VueAnalytics;
>
>declare module 'vue/types/options' {
>  interface ComponentOptions<V extends _Vue> {
>    ga?: VueAnalytics;
>  }
>}
>
>declare module 'vue/types/vue' {
>  interface Vue {
>    $ga: VueAnalytics;
>  }
>}
> ```

This file lives in a '@types' directory in the src directory of my Vue project, where I keep similar files for other plugins that don't have builtin typescript support.
I then have a single file (alltypes.d.ts) in that same '@types' directory that includes the line
`declare module 'vue-analytics'` as well as similar lines for each of the other declaration files.

This has solved the problem for me.

**Comment by MatteoGabriele** [comment] 2019-08-19 07:22
this is a duplicate ticket indeed see #161 
sorry but at this moment is not on top of my list but, if someone has time, a PR is always welcomed!

thanks :)

**Closed by MatteoGabriele** 2019-08-19 07:22 UTC
