### ISSUE TITLE
Attributes' screenview conflict

### ISSUE THREAD

**Issue by zhougonglai** [MatteoGabriele/vue-analytics#159] opened 2018-09-07 10:45 UTC
e. 'Route name property is mandatory' means all routing to add the name or don't add?
i think is 'all routing to add the name', But it is still an error 
```bash
'[vue-analytics] Route name is mandatory when using screenview.' 
```
----
```javascript
Vue.use(VueAnalytics, {
  id: 'UA-xxxx',
  checkDuplicatedScript: true,
  router, store,
  autoTracking: {
    screenview: true,
    skipSamePath: true,
    exception: true
  },
  commands: {...})
```
----
router.js
```javascript
routes: [
    {
      path: '/',
      name: 'home',
      component: () => import(/* webpackChunkName: "about" */ '@/views/Home.vue')
    },
    {
      path: '/about',
      name: 'about',
      component: () => import(/* webpackChunkName: "about" */ '@/views/About.vue')
    },
    {
      path: '/positions',
      name: 'positions',
      component: () => import(/* webpackChunkName: "positions" */ '@/views/Positions.vue')
    },
    {
      path: '/dashboard',
      name: 'dashboard',
      component: () => import(/* webpackChunkName: "Dashboard" */ '@/views/Dashboard.vue')
    }
  ]
```

**Comment by MatteoGabriele** [comment] 2018-09-08 21:39
Unfortunately it's already an issue #149 So I will close this one
The problem is that VueRouter creates an empty route object at the beginning and then populates it with routes data. Due to the dynamic imports, this process is slightly slower and doesn't happen immediately so the route appears to have `name` as `null`.
I don't know how to fix it and there's a ticket already open to vue-router repo but ... doesn't look good, so far 🤣 
We'll see! Probably I'll come up with a solution before.

**Closed by MatteoGabriele** 2018-09-08 21:39 UTC
