### ISSUE TITLE
137:1 Uncaught (in promise) Error: [vue-analytics] Route name is mandatory when using screenview.

### ISSUE THREAD

**Issue by NoraGithub** [MatteoGabriele/vue-analytics#149] opened 2018-08-12 05:22 UTC
### Description

It reminds me of `137:1 Uncaught (in promise) Error: [vue-analytics] Route name is mandatory when using screenview.` unexpectedly.

### Expected behavior

```
export function createApp (store, router ,axios) {

  // sync the router with the vuex store.
  // this registers `store.state.route`
  sync(store, router)

  // create the app instance.
  // here we inject the router, store and ssr context to all child components,
  // making them available everywhere as `this.$router` and `this.$store`.
  Vue.prototype.$axios = axios
  VueAnalyticsConfig.router = router
  let isDebug = process.env.NODE_ENV === 'production'
  Vue.use(VueAnalytics, Vue.prototype.$lodash.merge(VueAnalyticsConfig,{
    autoTracking: {
      screenview: true
    },
    debug: {
      sendHitTask: isDebug,
      enabled: isDebug,
    }
  }))

```

I did it as above and I don't expect any errors in console.

### Actual behavior

It reminds me of `137:1 Uncaught (in promise) Error: [vue-analytics] Route name is mandatory when using screenview.` unexpectedly.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: vue-analytics@5.12.3 

Then, specify:

1. Operating system: OS X 10.11.3 (15D21)
2. Browser and version:Version 68.0.3440.106 (Official Build) (64-bit)

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by NoraGithub** [comment] 2018-08-12 05:55
It checkout route.name by [route.currentRoute](https://github.com/MatteoGabriele/vue-analytics/blob/master/src/lib/page.js#L87)and 
however, VueRoute init with null.
4.
```
  get currentRoute (): ?Route {
    return this.history && this.history.current
  }
``` 
[link](https://github.com/vuejs/vue-router/blob/05a5f085fd7e230d4b51862f7a6086fec4378bc6/src/index.js#L80)
3.
```
      case 'history':
        this.history = new HTML5History(this, options.base)
        break
```
[link](https://github.com/vuejs/vue-router/blob/05a5f085fd7e230d4b51862f7a6086fec4378bc6/src/index.js#L56)
2.`this.current = START`
[link](https://github.com/vuejs/vue-router/blob/05a5f085fd7e230d4b51862f7a6086fec4378bc6/src/history/base.js#L32)
1. 
```
export const START = createRoute(null, {
  path: '/'
})
```
[link](https://github.com/vuejs/vue-router/blob/05a5f085fd7e230d4b51862f7a6086fec4378bc6/src/util/route.js#L32)

**Comment by MatteoGabriele** [comment] 2018-08-13 07:07
Hi @NoraGithub 
thanks for your feedback but I'm sorry i don't understand the problem.

I need you to create a small app using vue-cli maybe. just a small app with minimal necessary to reproduce this error and then paste the link here in the issue

**Comment by NoraGithub** [comment] 2018-08-13 16:07
Here's the [demo](https://github.com/NoraGithub/vue-router-analytics)

If any other things I can help, please let me know.

**Comment by MatteoGabriele** [comment] 2018-08-14 06:12
@NoraGithub 
thanks for the demo.
So first problem, which is the one that vue-analytics is warning you, is that to be able to autotrack your routes, you need to add a `name` property to your routes.

example

```js
import Home from '@/components/Home

const routes = [
  { name: 'Home', path: '/', component: Home }
]
```

Other error I see in the example is that you are not passing the `router` instance to your Vue instance and also that your trying to use `template` for a quick component but you're using the run-time build and it doesn't work.

The main error though, is just caused by a missing `name` property in your routes

**Comment by NoraGithub** [comment] 2018-08-14 20:06
@MatteoGabriele  Thanks for you quick feedback.

My fault for the carelessness. I started the demo with vue-cli, so there were some typos.
I have updated the demo already that I passed `name` to routes and pass the router instance to vue instance. However, there comes the same error.
Would you please review it ? [updated demo](https://github.com/NoraGithub/vue-router-analytics)

**Comment by NoraGithub** [comment] 2018-08-16 07:12
@MatteoGabriele  Is there anything I can do for this issue?

**Comment by MatteoGabriele** [comment] 2018-08-16 07:49
Hey @NoraGithub 
I still think that you have made few mistakes in your example that are you probably reflecting in your project as well.

Talking about this demo: 

- you are not adding a `router-view` so you never used a route
- you are on that path '/' but you never register a route that matches a '/' path, only '/foo' and '/bar'.
- you still use a template component on a run-time only build, but you don't see that error because you never reach one of your route at all

I hope this make sense to you

**Comment by NoraGithub** [comment] 2018-08-16 07:57
I will try  to fix it all later and reply here.

**Comment by NoraGithub** [comment] 2018-08-16 11:40
https://github.com/NoraGithub/vue-router-analytics

There came the same error. Please review it again.
@MatteoGabriele

**Comment by NoraGithub** [comment] 2018-08-17 13:51
@MatteoGabriele  Are there anything wrong I had done?

**Comment by MatteoGabriele** [comment] 2018-08-17 14:39
I didn't have time to check it yet, I'll let you know asap

**Comment by MatteoGabriele** [comment] 2018-08-27 14:19
So I have checked and the issue seems to be the fact that we're giving a promise of a component to vue-router, and not a component.
This is a good pattern for code splitting but apparently delays the code that evaluates the `$route` or `$router.currentRoute` property which will be `null` for an instant, only at the root route.

I'm not sure if I can fix this and if so to which repository should be better to complain: vue or vue-router.

I don't consider this one a bug in vue-analytics tho

**Comment by NoraGithub** [comment] 2018-08-30 11:59
@MatteoGabriele  Is it confirmed what the problem is ?

**Comment by aislerGitHub** [comment] 2019-01-23 19:32
@MatteoGabriele: any news regarding this issue? I have the same issue and I don't see any useful feedback on the other ticket

**Comment by MatteoGabriele** [comment] 2019-03-09 15:48
apparently no one cares about this issue so I'll close this ticket, I can't do much and so far only 2 people had it so... will see


cheers

**Closed by MatteoGabriele** 2019-03-09 15:48 UTC
Labels: third-party issue

**Comment by Hydrog3n** [comment] 2019-03-09 22:44
Nope I have too. :)

**Comment by MatteoGabriele** [comment] 2019-03-09 22:48
@Hydrog3n "nope I have too"? what does it mean?
also why thumbs down? it's a third party issue, it core team doesn't fix it I have no clue and I hate to keep this ticket open for no reasons
