### ISSUE TITLE
Not detecting window.location.hostname

### ISSUE THREAD

**Issue by sloan-holzman** [MatteoGabriele/vue-analytics#114] opened 2018-04-24 18:32 UTC
Hi!

I am trying to use vue-analytics, but am not receiving any data - except in localhost, where it works fine.

Our situation is unique, in that we have different domains for each customer.  So, the Google Analytics id should change depending on the hostname.

I've set the id to change depending on the window.location.hostname, but it still doesn't seem to work.

Could you please advise where I am going wrong?

Thanks,

Sloan

p.s. - code below...

```js
import Vue from 'vue';
import VueSession from 'vue-session';
import stitcher from './components/stitcher.vue';
import * as auth from '@companyname/auth';
import * as dashboard from '@companyname/dashboard';
// import * as lgc from '@companyname/final-lgc';
import * as tasking from '@companyname/tasking';
import * as help from '@companyname/help';
import Router from 'vue-router';
import notFound from './components/notFound.vue';
import terms from './components/Terms.vue';
import privacy from './components/Privacy.vue';
import permissionDenied from './components/permissionDenied.vue';
import Vuetify from 'vuetify';
import * as GoogleMaps from 'vue2-google-maps';
import {get} from 'lodash';
import {ready} from '@companyname/interservice';
import VueAnalytics from 'vue-analytics'

import VueQuillEditor from 'vue-quill-editor';
import 'vuetify/dist/vuetify.min.css';
import 'quill/dist/quill.core.css';
import 'quill/dist/quill.bubble.css';
import 'quill/dist/quill.snow.css';
import abilityPlugin from './config/ability-plugin';
import abilities from './config/abilities';

window.vueGoogleMapsInit();
Vue.use(GoogleMaps, {
  load: {
    key: 'asdfasdfasdfasdfasdf',
    libraries: 'places'
  }
});

Vue.use(Router);
Vue.use(VueSession);
Vue.use(VueQuillEditor);
Vue.use(Vuetify);
Vue.use(abilityPlugin, abilities);

const router = new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'dashboard',
      component: dashboard.app,
      meta: { requiresAuth: true },
      children: dashboard.routes()
    },
    {
      path: '/auth',
      component: auth.app,
      children: auth.routerConfig(),
      meta: {featureName: 'auth'}
    },
    /*
    {
      path: '/lgc',
      name: 'lgc',
      component: lgc.app,
      meta: {requiresAuth: true, featureFlag: {feature: 'lgc', description: 'LGC'}}
    },
    */
    {
      path: '/tasking',
      component: tasking.app,
      meta: {requiresAuth: true, featureName: 'tasking'},
      children: tasking.routes()
    },
    {
      path: '/assignment/task/:taskId',
      redirect: to => '/tasking' + to.path,
      props: true
    },
    {
      path: '/answers/task/:taskId',
      redirect: to => '/tasking' + to.path
    },
    {
      path: '/help',
      name: 'help',
      component: help.app,
      children: help.routes()
    },
    {
      path: '/terms',
      name: 'terms',
      component: terms
    },
    {
      path: '/privacy',
      name: 'privacy',
      component: privacy
    },
    {
      path: '/permissiondenied',
      name: 'permissiondenied',
      component: permissionDenied
    },
    {
      path: '*',
      component: notFound
    }
  ]
});

router.beforeEach(async (to, from, next) => {
  if (to.matched.some(record => record.meta.requiresAuth)) {
    let redirectPath;
    const loggedIn = await ready;
    const user = loggedIn.user || null;
    const featureFlag = get(to, 'meta.featureFlag.feature');
    if (!loggedIn) {
      if (localStorage.loggedOut && localStorage.loggedOut === 'true') {
        redirectPath = '/';
      } else {
        redirectPath = to.fullPath;
      }
      localStorage.loggedOut = 'done';
      next({
        path: '/auth',
        query: { redirect: redirectPath }
      });
    } else if (featureFlag) {
      const allowed = get(user, `featureFlags.${featureFlag}`);
      const description = get(to, 'meta.featureFlag.description');
      const fullPath = to.fullPath;
      if (allowed) {
        next();
      } else {
        next({
          path: '/permissiondenied',
          query: { description, fullPath }
        });
      }
    } else {
      next();
    }
  } else {
    next(); // make sure to always call next()!
  }
});

function getClientId(environment) {
  let uaId;
  switch (environment) {
    case 'customer1.companysite.com':
      uaId = 'UA‌-123456789-1';
      break;
    case 'customer2.companysite.com':
      uaId = 'UA‌-123456789-2';
      break;
    case 'customer3.companysite.com':
      uaId = 'UA‌-123456789-3';
      break;
    case 'customer4.companysite.com':
      uaId = 'UA‌-123456789-4';
      break;
    case 'customer5.companysite.com':
      uaId = 'UA‌-123456789-5';
      break;
    case 'customer6.companysite.com':
      uaId = 'UA‌-123456789-6';
      break;
    case 'customer7.companysite.com':
      uaId = 'UA‌-123456789-7';
      break;
    case 'customer8.companysite.com':
      uaId = 'UA‌-123456789-8';
      break;
    case 'localhost':
      uaId = 'UA‌-123456789-9';
      break;
    default:
      uaId = 'no_id';
      break;
  }
  console.log('id', uaId);
  return uaId;
}

let clientID = getClientId(window.location.hostname);

if (clientID !== 'no_id') {
  Vue.use(VueAnalytics, {
    id: clientID,
    router
  });
}

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  render: h => h(stitcher)
});

```

**Comment by MatteoGabriele** [comment] 2018-04-25 10:04
hi @sloan-holzman 
I cannot really have a solution for you, to be honest. The code seems ok, but there are "too many" things that could go wrong outside this snippet.

I would suggest as a first step to enable debugging even in production to see if vue-analytics starts and with which values. That would probably be the starting point for me.

I have to close this ticket because is not related to the plug-in itself, but more on your setup.

Let me know if you find the cause of it. 

Feel free to open a new issue filling the template and providing a small vue-cli application with the problem in it, if you find out that is an actual bug

**Closed by MatteoGabriele** 2018-04-25 10:04 UTC

**Comment by sloan-holzman** [comment] 2018-04-25 17:51
Thanks, Matteo.

I think it was a simple typo!
